name: "Create a Persistent Cache"
description: "Create a persistent cache using git"



inputs:
  repo_name:
    description: "Name of the repositry to be used for cache"
    required: true
  token:
    description: "token for cloning"
    required: true
  filename:
    description: "file to be cache "
    required: true
  cache_name:
    description: "unique cache name to be refrenced"
    required: true
  actiontype:
    description: "Actiontype STORE RETRIEVE"
    required: true

  runs:
    using: composite
    steps: 
      - name: Store file in cache
        env:
          cachetoken: ${{inputs.token}}
          gitrepo:  ${{inputs.repo_name}}
          filename:  ${{inputs.filename}}
          cachename:  ${{inputs.cache_name}}
          gitrepo:  ${{inputs.repo_name}}
      run: |
          mkdir cacherepo
          cd ./cacherepo
          git clone https://$cachetoken@github.com/gitrepo
          export dir=`ls`
          cd $dir
          mkdir $cachename
          cp $filename ./$cachename/
          git add ./$cachename/$filename
          git commit -m "$cachename"
          git push
        
    
